name: Unity WebGL Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          docker-images: true

      - name: Unity Builder
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          unityVersion: 6000.3.10f1
          customParameters: -nographics -batchmode -username "${{ secrets.UNITY_EMAIL }}" -password "${{ secrets.UNITY_PASSWORD }}"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/WebGL/Web
          branch: gh-pages